LanchesMac/ViewModels/HomeViewModel.cs
using LanchesMac.Models;

namespace LanchesMac.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Lanche> LanchesPreferidos { get; set; }
    }
}

LanchesMac/Controllers/HomeController.cs
using LanchesMac.Models;
using LanchesMac.Repositories.Interfaces;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LanchesMac.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILancheRepository _lancheRepository;

        public HomeController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        public IActionResult Index()
        {
            var homeViewModel = new HomeViewModel
            {
                LanchesPreferidos = _lancheRepository.LanchesPreferidos
            };

            return View(homeViewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None,
            NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel
            {
                RequestId = Activity.Current?.Id
                ?? HttpContext.TraceIdentifier
            });
        }
    }
}

LanchesMac/Controllers/LancheController.cs
using LanchesMac.Models;
using LanchesMac.Repositories.Interfaces;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class LancheController : Controller
    {//vai injetar o serviço como repositório, ja foi definido os serviços em startup.cs!
        private readonly ILancheRepository _lancheRepository;
        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        //vai listar os lanches
        public IActionResult List(string categoria)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRepository.Lanches.OrderBy(l => l.LancheId);
                categoriaAtual = "Todos os lanches";
            }
            else
            {
                //if (string.Equals("Normal", categoria, StringComparison.OrdinalIgnoreCase))
                //{
                //    lanches = _lancheRepository.Lanches
                //        .Where(l => l.Categoria.CategoriaNome.Equals("Normal"))
                //        .OrderBy(l => l.Nome);
                //}
                //else
                //{
                //    lanches = _lancheRepository.Lanches
                //       .Where(l => l.Categoria.CategoriaNome.Equals("Natural"))
                //       .OrderBy(l => l.Nome);
                //}
                lanches = _lancheRepository.Lanches
                          .Where(l => l.Categoria.CategoriaNome.Equals(categoria))
                          .OrderBy(c => c.Nome);

                categoriaAtual = categoria;
            }

            /*passagem de dados da controller para a view
            ViewData["Titulo"] = "Todos os Lanches";
            ViewData["Data"] = DateTime.Now;*/

            //lista de lanches
            //var lanches = _lancheRepository.Lanches;
            //return View(lanches);

            //instancia
            var lanchesListViewModel = new LancheListViewModel
            {//utilizar a instancia pra pegar as 2 propriedades abaixo
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            };

            return View(lanchesListViewModel);
        }

        public IActionResult Details(int lancheId)
        {
            var lanche = _lancheRepository.Lanches.FirstOrDefault(l => l.LancheId == lancheId);
            return View(lanche);
        }

        public ViewResult Search(string searchString)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(searchString))
            {
                lanches = _lancheRepository.Lanches.OrderBy(p => p.LancheId);
                categoriaAtual = "Todos os Lanches";
            }
            else
            {
                //if (string.Equals("Normal", categoria, StringComparison.OrdinalIgnoreCase))
                //{
                //    lanches = _lancheRepository.Lanches
                //        .Where(l => l.Categoria.CategoriaNome.Equals("Normal"))
                //        .OrderBy(l => l.Nome);
                //}
                //else
                //{
                //    lanches = _lancheRepository.Lanches
                //       .Where(l => l.Categoria.CategoriaNome.Equals("Natural"))
                //       .OrderBy(l => l.Nome);
                //}
                lanches = _lancheRepository.Lanches
                          .Where(p => p.Nome.ToLower().Contains(searchString.ToLower()));
                if (lanches.Any())
                {
                    categoriaAtual = "Lanches";
                }
                else
                {
                    categoriaAtual = "Nenhum lanche foi encontrado";
                }
            }
                return View("~/Views/Lanche/List.cshtml", new LancheListViewModel
                {
                    Lanches = lanches,
                    CategoriaAtual = categoriaAtual
                });


            /*public IActionResult Details(int lancheId)
            {
                //obter o lanche do repositório, acessar tabela e retornar a view do lanche
                var lanche = _lancheRepository.Lanches.FirstOrDefault(l => l.LancheId == lancheId);
                return View(lanche);
            }*/
        }
    }
}

LanchesMac/Views/Home/Index.cshtml
<div class="row text-center">
    <h2>Lanches</h2>
</div>

<div class="container">
    <section id="sobre">
      <div class="row justify-content-center">
            <div class="col-xs-12 col-sm-6 col-md-3 text-center">
                <img src="~/images/leiaute/icons8-love-50.png" />
                <h3>Feitos com amor</h3>
                <p class="text-muted">Fazemos seu lanche com carinho.</p>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 text-center">
                <img src="~/images/leiaute/icons8-get-dressed-50.png" />
                <h3>Prontos para entrega</h3>
                <p class="text-muted">Entregamos o seu pedido</p>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 text-center">
             <img src="~/images/leiaute/icons8-desconto-48.png" />
                <h3>Preços Camaradas </h3>
                <p class="text-muted">Promoções imperdíveis.</p>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 text-center">
               <img src="~/images/leiaute/icons8-comida-natural-50.png" />
                <h3>Lanches Naturais</h3>
                <p class="text-muted">...saudáveis e naturais...</p>
            </div>
        </div>
    </section>

    <section id="portfolio">
        @await Html.PartialAsync("_IndexPartial")
    </section>

     <br />
    
    <section id="contato">
         <div class="row">
             <div class="col-10 col-md-5 col-lg-5 offset-1" style="color: black">
                 <h4> &copy; 2021 - LanchesMac</h4>
                 <p class="text-justify">
                     Aqui você encontra aquele lanche gostoso que da água na boca.
                     Aquela sobremesa saborosa e para acompanhar a sua bebida preferida.
                     E se você é vegetariano também vai encontrar o lanche, sobremesa e bebida do seu gosto.
                 </p>
             </div>

             <div class="col-10 col-md-5 col-lg-5 offset-1" style="color: black">
                 <h4>Tem alguma dúvida ?</h4>
                 <ul class="list-unstyled">
                     <li class="py-1"> Praça IV Centenário, 1 - 2º Andar sala 3</li>
                     <li class="py-1"> +55 11 9 4313-3213</li>
                     <li class="py-1"> <a href="lanchesmac@hotmail.com" style="color: blue">lanchesmac@hotmail.com</a></li>
                 </ul>
             </div>
         </div>
    </section>

</div>

LanchesMac/Views/Home/_IndexPartial.cshtml
<div class="row no-gutter">
    @{
         string[] imgs = {
                        "~/images/carousel11.jpg",
                        "~/images/carousel12.jpg",
                        "~/images/carousel13.jpg",
                        "~/images/carousel14.jpg",
                        "~/images/carousel17.jpg"
             };
    }

    @foreach (var img in imgs)
    {
        <div class="col-xs-2 col-md-2">
            <a class="portfolio-box" asp-action="List" asp-controller="Lanche">
                <img src="@Url.Content(img)" alt="Lanches" width="450" height="220"/>
            </a>
        </div>
    }
</div>