LanchesMac/Areas/Admin/Controllers/AdminGraficoController.cs
using LanchesMac.Areas.Admin.Servicos;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminGraficoController : Controller
    {
        private readonly GraficoVendasService _graficoVendas;

        public AdminGraficoController(GraficoVendasService graficoVendas)
        {
            _graficoVendas = graficoVendas ?? throw
                new ArgumentNullException(nameof(graficoVendas));
        }
        public JsonResult VendasLanches(int dias)
        {
            var lanchesVendasTotais = _graficoVendas.GetVendasLanches(dias);
            //esta vindo como lista, porém é necessário json
            return Json(lanchesVendasTotais);
        }
        [HttpGet]
        public IActionResult Index(int dias)
        {
            return View();
        }
        [HttpGet]
        public IActionResult VendasMensal(int dias)
        {
            return View();
        }

        [HttpGet]
        public IActionResult VendasSemanal(int dias)
        {
            return View();
        }
    }
}

LanchesMac/Areas/Admin/Views/AdminGrafico/Index.cshtml
<title>
    @ViewData["Title"] - Gráfico de Vendas
</title>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div id="chart_div" style="width: 900px; height: 500px;"></div>
<script type="text/javascript">
    google.charts.load('current', { 'packages': ['corechart'] });

    google.charts.setOnLoadCallback(CarregaDados);

    function CarregaDados(){
        $.ajax({
            url: '@Url.Action("VendasLanches", "AdminGrafico")',
            data: {dias: 360},
            dataType: "json",
            type: "GET",
            error: function(xhr, status, error){
                var err = eval("("+ xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function(data){
                GraficoVendasLanches(data);
                return false;
            }
        });
    }
    //recebendo dados no formato array
    function GraficoVendasLanches(data){
        var dataArray = [
            ['Lanche','Quantidade', 'Valores(R$)']
        ];
        //incluindo dados em um array
        $.each(data, function (i,item){
            dataArray.push([item.lancheNome, item.lanchesQuantidade, item.lanchesValorTotal]);
        });
        //convertendo para data table
        var data = google.visualization.arrayToDataTable(dataArray);
        //definindo opções do grafico
        var options = {
            title: 'Lanches - Vendas nos últimos 360 dias',
            chartArea:{
                width:'70%'
            },
            colors:['#5202b5','#d2a828'],
            minValue: 0
        },
        vAxis:{
            title:'Lanches'
        }
    };

    var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
    //dados são inicializados e exibidos usando as opções de grafico definidas
    chart.draw(data,options);

    return false;
</script>